import { TemplateConfig } from "@/types";

export const TEMPLATES: TemplateConfig[] = [
  {
    id: "saas-launch",
    name: "SaaS Launch",
    category: "saas",
    description: "Conversion-optimized product landing page with pricing tiers and feature grids.",
    accent: "#1a6cf6",
    estimatedBuildSec: 18,
    mlFeatures: ["Copy optimization", "CTA A/B predictor", "Churn intent classifier"],
    sections: [
      { id: "hero", type: "hero", config: { headline: "AI-generated", layout: "split", cta: "Start free" } },
      { id: "features", type: "features", config: { columns: 3, icons: true } },
      { id: "pricing", type: "pricing", config: { tiers: 3, toggle: "monthly/annual" } },
      { id: "testimonials", type: "testimonials", config: { style: "grid" } },
      { id: "cta", type: "cta", config: { style: "banner" } },
    ],
  },
  {
    id: "ecommerce-boutique",
    name: "E-Commerce Boutique",
    category: "ecommerce",
    description: "Curated product store with AI-powered recommendations and smart search.",
    accent: "#c4503a",
    estimatedBuildSec: 24,
    mlFeatures: ["Product recommendation (collab filter)", "Search intent classifier", "Price elasticity model"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "fullbleed", overlay: true } },
      { id: "gallery", type: "gallery", config: { grid: "masonry", filters: true } },
      { id: "features", type: "features", config: { style: "minimal" } },
      { id: "cta", type: "cta", config: { style: "split" } },
    ],
  },
  {
    id: "portfolio-creative",
    name: "Creative Portfolio",
    category: "portfolio",
    description: "Visually bold case study showcase with generative layout system.",
    accent: "#7c3aed",
    estimatedBuildSec: 14,
    mlFeatures: ["Project categorizer", "Aesthetic score model", "Client fit predictor"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "editorial", animated: true } },
      { id: "gallery", type: "gallery", config: { grid: "editorial", hover: "expand" } },
      { id: "contact", type: "contact", config: { style: "minimal" } },
    ],
  },
  {
    id: "blog-publication",
    name: "Editorial Publication",
    category: "blog",
    description: "Long-form content platform with semantic search and topic clustering.",
    accent: "#1a1a1a",
    estimatedBuildSec: 16,
    mlFeatures: ["Topic clustering (LDA)", "Semantic search embeddings", "Read-time estimator"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "editorial", featuredPost: true } },
      { id: "gallery", type: "gallery", config: { style: "list", categories: true } },
      { id: "cta", type: "cta", config: { style: "newsletter" } },
    ],
  },
  {
    id: "restaurant-fine",
    name: "Fine Dining",
    category: "restaurant",
    description: "Atmosphere-first restaurant site with reservation flow and menu builder.",
    accent: "#8b6914",
    estimatedBuildSec: 12,
    mlFeatures: ["Menu popularity ranker", "Reservation demand forecast", "Sentiment from reviews"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "cinematic", overlay: "dark" } },
      { id: "gallery", type: "gallery", config: { style: "polaroid" } },
      { id: "features", type: "features", config: { style: "menu" } },
      { id: "contact", type: "contact", config: { style: "reservation" } },
    ],
  },
  {
    id: "realestate-agency",
    name: "Real Estate Agency",
    category: "realestate",
    description: "Property listing platform with price prediction and neighbourhood scoring.",
    accent: "#065f46",
    estimatedBuildSec: 22,
    mlFeatures: ["Property price regressor", "Lead quality scorer", "Neighborhood cluster model"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "search-prominent" } },
      { id: "gallery", type: "gallery", config: { grid: "card-list", filters: true } },
      { id: "features", type: "features", config: { style: "stats" } },
      { id: "contact", type: "contact", config: { style: "agent-card" } },
    ],
  },
  {
    id: "healthcare-clinic",
    name: "Healthcare Clinic",
    category: "healthcare",
    description: "Trust-forward medical practice site with symptom triage and appointment flow.",
    accent: "#0369a1",
    estimatedBuildSec: 20,
    mlFeatures: ["Symptom triage classifier", "Appointment demand predictor", "FAQ semantic retrieval"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "calm", trust: true } },
      { id: "features", type: "features", config: { style: "services" } },
      { id: "faq", type: "faq", config: { powered: "semantic-search" } },
      { id: "contact", type: "contact", config: { style: "booking" } },
    ],
  },
  {
    id: "education-course",
    name: "Online Course Platform",
    category: "education",
    description: "Course marketplace with adaptive learning paths and progress prediction.",
    accent: "#9d174d",
    estimatedBuildSec: 26,
    mlFeatures: ["Learning path optimizer", "Dropout risk predictor", "Knowledge graph builder"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "course-preview" } },
      { id: "features", type: "features", config: { style: "curriculum" } },
      { id: "testimonials", type: "testimonials", config: { style: "video-grid" } },
      { id: "pricing", type: "pricing", config: { tiers: 2 } },
      { id: "cta", type: "cta", config: { style: "urgency" } },
    ],
  },
  {
    id: "agency-studio",
    name: "Creative Agency",
    category: "agency",
    description: "Bold brand-forward agency site with case study depth and lead qualification.",
    accent: "#dc2626",
    estimatedBuildSec: 18,
    mlFeatures: ["Lead qualification scorer", "Project fit classifier", "Budget estimator model"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "statement", kinetic: true } },
      { id: "gallery", type: "gallery", config: { style: "case-studies" } },
      { id: "features", type: "features", config: { style: "process" } },
      { id: "contact", type: "contact", config: { style: "project-brief" } },
    ],
  },
  {
    id: "startup-product",
    name: "Startup Product",
    category: "startup",
    description: "High-velocity launch page with waitlist scoring and viral loop mechanics.",
    accent: "#0f172a",
    estimatedBuildSec: 15,
    mlFeatures: ["Waitlist priority scorer", "Viral coefficient estimator", "ICP fit classifier"],
    sections: [
      { id: "hero", type: "hero", config: { layout: "product-demo", waitlist: true } },
      { id: "features", type: "features", config: { columns: 2, style: "benefit-led" } },
      { id: "testimonials", type: "testimonials", config: { style: "logos" } },
      { id: "cta", type: "cta", config: { style: "countdown" } },
    ],
  },
];

export const getTemplate = (id: string) => TEMPLATES.find((t) => t.id === id);
